default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2

development:
  <<: *default
  database: chitter

test:
  <<: *default
  database: chitter_test

production:
  <<: *default
  database: chitter